export const stationTemplate = {
  id: "[Ex: REVALIDA_FACIL]",
  numero: "[Ex: 1]",
  especialidade: "[Ex: CLÍNICA MÉDICA]",
  tempoDuracao: 10,
  palavrasChave: ["[Ex: Palavra1]", "[Ex: Palavra2]", "[Ex: Palavra3]", "[Ex: Palavra4]", "[Ex: Palavra5]"],
  nivelDificuldade: "[Ex: Fácil]",
  instrucoesParticipante: {
    cenarioAtendimento: {
      nivelAtencao: "[Ex: Atenção primária à saúde]",
      tipoAtendimento: "[Ex: Ambulatorial]",
      infraestruturaUnidade: [
        "[Ex: Consultório equipado]",
        "[Ex: Laboratório de análises clínicas (resultados forne)]"
      ],
    },
    descricaoCompletaCaso: "[Descrever brevemente a situação inicial e a queixa principal do paciente. Ex: Paciente de [idade] anos, sexo [masculino/feminino], procura atendimento com queixa de [queixa principal] há [tempo].]",
    tarefasPrincipais: [
      "[Ex: Realizar a anamnese.]",
      "[Ex: Realizar o exame físico geral.]",
    ],
  },
  instrucoesAtor: {
    nomePacienteSimulado: "[Nome fictício]",
    respostaOutrasPerguntas: "\"Não consta no script\" ou \"Não sei informar\".",
    perguntasPaciente: [
      "[Ex: \"Doutor(a), o meu caso é grave?\"]",
    ],
  },
  avisosImportantes: [
    "[Ex: O TOQUE NO PACIENTE SIMULADO É PERMITIDO APENAS PARA OS PROCEDIMENTOS DE EXAME FÍSICO DESCRITOS NAS TAREFAS.]",
    "[Ex: TODOS OS RESULTADOS DE EXAMES COMPLEMENTARES SOLICITADOS SERÃO FORNECIDOS IMPRESSOS PELO AVALIADOR QUANDO PERTINENTE.]",
  ],
  dadosPacienteSimulado: {
    motivoConsulta: "\"[Citar a queixa principal exatamente como o paciente falaria. Ex: 'Estou com uma dor forte no peito há duas horas.']\"",
    detalheSintomas: [
      {
        nomeSintoma: "[Nome do Sintoma. Ex: Dor Torácica]",
        inicio: "[Resposta do ator. Ex: 'Começou de repente, há umas duas horas.']",
        localizacao: "[Resposta do ator. Ex: 'Bem aqui no meio do peito.']",
        irradiacao: "[Resposta do ator. Ex: 'Sinto que vai para o meu braço esquerdo e pescoço.']",
        qualidadeTipo: "[Resposta do ator. Ex: 'É uma dor tipo aperto, uma pressão forte.']",
        intensidade: "[Resposta do ator. Ex: 'Agora está um 8. Começou mais forte, um 9.']",
        duracao: "[Resposta do ator. Ex: 'Desde que começou, não parou mais.']",
        fatoresMelhora: "[Resposta do ator. Ex: 'Nada que eu fiz melhorou.']",
        fatoresPiora: "[Resposta do ator. Ex: 'Quando eu tento respirar fundo, parece que piora.']",
        evolucao: "[Resposta do ator. Ex: 'Começou forte e continua forte.']",
      },
    ],
    sintomasAcompanhantes: {
      febre: "[Resposta. Ex: 'Não tive febre.']",
      dispneia: "[Resposta. Ex: 'Sim, estou com falta de ar.']",
      nauseasVomitos: "[Resposta. Ex: 'Senti um pouco de enjoo, mas não vomitei.']",
      sudorese: "[Resposta. Ex: 'Sim, estou suando frio.']",
      palpitacoes: "[Resposta]",
      tosseExpectoração: "[Resposta]",
      sintomasNeurologicos: "[Resposta]",
      sintomasGastrointestinais: "[Resposta]",
      outrosSintomas: "[Resposta]",
    },
    medicacoesAlivio: "[Resposta. Ex: 'Tomei um comprimido para dor que tinha em casa, mas não adiantou. Não lembro o nome.']",
    antecedentesPessoais: {
      doencasPrevias: "[Resposta. Ex: 'Tenho pressão alta e diabetes.']",
      medicamentosUsoContinuo: "[Resposta. Ex: 'Uso Losartana 50mg de manhã e Metformina 850mg duas vezes ao dia.']",
      alergias: "[Resposta. Ex: 'Tenho alergia a dipirona.']",
      cirurgiasPrevias: "[Resposta. Ex: 'Fiz cirurgia de apendicite quando era criança.']",
      internacoesPrevias: "[Resposta]",
      vacinacao: "[Resposta. Ex: 'Tomei as vacinas da COVID e da gripe este ano. Outras não lembro.']",
      ginecoObstetricos: {
        dum: "[Data da Última Menstruação]",
        intercorrenciasGravidezAnterior: "[Resposta]",
        intercorrenciasPrePosParto: "[Resposta]",
        gestaParaAborto: "[G P A]",
        usoContraceptivos: "[Resposta]",
      },
    },
    habitosVida: {
      alimentacao: "[Resposta. Ex: 'Como de tudo, mas gosto muito de fritura e doce.']",
      atividadeFisica: "[Resposta. Ex: 'Não faço exercício.']",
      alcool: "[Resposta. Ex: 'Bebo cerveja nos finais de semana, umas 4-5 latinhas.']",
      tabagismo: "[Resposta. Ex: 'Fumo um maço de cigarros por dia há 20 anos.']",
      drogasIlicitas: "[Resposta. Ex: 'Não uso.']",
      sono: "[ higiene do sono, se dorme bem, se acorda de noite.]",
    },
    historiaPsicossocialEpidemiologica: {
      ocupacao: "[Resposta. Ex: 'Sou motorista de caminhão.']",
      moradiaSaneamento: "[Resposta. Ex: 'Moro em casa com água encanada e esgoto.']",
      viagensRecentes: "[Resposta. Ex: 'Não viajei ultimamente.']",
      contatoDoentesAnimais: "[Resposta. Ex: 'Meu vizinho estava gripado semana passada. Tenho um cachorro em casa.']",
      exposicaoAmbiente: "[Resposta, se pertinente ao caso. Ex: 'Na minha rua tem muito mosquito da dengue.']",
    },
    historiaFamiliar: "[Resposta. Ex: 'Meu pai morreu de infarto com 50 anos. Minha mãe tem pressão alta.']",
    contatosSintomasSimilares: "[Resposta. Ex: 'Que eu saiba, não.']",
  },
  impressosDisponiveis: [
    {
      id: "[Ex: estX_examefisico_geral]",
      tipo: "EXAME FÍSICO GERAL E SINAIS VITAIS",
      conteudo: {
        estadoGeral: "[Ex: Regular, consciente, orientado, hidratado, corado, acianótico, anictérico, febril/afebril.]",
        fc: "[Valor] bpm",
        fr: "[Valor] irpm",
        pa: "[Valor] x [Valor] mmHg (MMSS D/E)",
        saturacaoO2: "[Valor]% (ar ambiente / O2 suplementar a X L/min)",
        tax: "[Valor]ºC",
        peso: "[Valor] kg",
        altura: "[Valor] m",
        imc: "[Valor] kg/m²",
      },
    },
    {
      id: "[Ex: estX_examefisico_cardiovascular]",
      tipo: "EXAME FÍSICO ESPECÍFICO",
      sistemaRegiao: "[Sistema/Região]",
      conteudo: {
        inspecao: "[Achados]",
        palpacao: "[Achados]",
        percussao: "[Achados]",
        ausculta: "[Achados. Ex: Cardiovascular: Bulhas rítmicas, normofonéticas, em 2 tempos, sem sopros. Respiratório: Murmúrio vesicular universalmente audível, sem ruídos adventícios.]",
        outrosAchados: "[Ex: Abdômen: Flácido, indolor à palpação, RHA+, sem visceromegalias.]",
      },
    },
    {
      id: "[Ex: estX_lab_hemograma]",
      tipo: "RESULTADO DE EXAMES LABORATORIAIS",
      tipoExame: "[Tipo de Exame]",
      conteudo: {
        hemograma: {
          hemoglobina: "[Valor] g/dL (Ref: [Valores de Referência])",
          hematocrito: "[Valor]% (Ref: [Valores de Referência])",
          leucocitosTotais: "[Valor]/mm³ (Ref: [Valores de Referência])",
          neutrofilos: "[Valor]% ([Valor Absoluto])",
          linfocitos: "[Valor]% ([Valor Absoluto])",
          monocitos: "[Valor]% ([Valor Absoluto])",
          eosinofilos: "[Valor]% ([Valor Absoluto])",
          basofilos: "[Valor]% ([Valor Absoluto])",
          plaquetas: "[Valor]/mm³ (Ref: [Valores de Referência])",
        },
        bioquimica: {
          glicemiaJejum: "[Valor] mg/dL (Ref: [Valores de Referência])",
          ureia: "[Valor] mg/dL (Ref: [Valores de Referência])",
          creatinina: "[Valor] mg/dL (Ref: [Valores de Referência])",
          sodio: "[Valor] mEq/L (Ref: [Valores de Referência])",
          potassio: "[Valor] mEq/L (Ref: [Valores de Referência])",
          enzimasCardiacas: "[Valores]",
          funcaoHepatica: "[Valores]",
        },
        outrosExames: "[Ex: Urina tipo I, PCR, VHS, Gasometria Arterial, etc.]",
      },
    },
    {
      id: "[Ex: estX_imagem_raiox_torax]",
      tipo: "RESULTADO DE EXAME DE IMAGEM",
      tipoExame: "[Tipo de Exame]",
      conteudo: {
        descricaoLaudo: "[Descrever os achados principais do exame de imagem. Ex: Radiografia de Tórax PA e Perfil: Parênquima pulmonar sem opacidades ou consolidações. Área cardíaca de dimensões normais. Seios costofrênicos livres.]",
        caminhoImagem: "[Pode-se ter uma imagem real para consulta do avaliador, mas o candidato recebe o laudo escrito ou uma imagem simplificada.]",
      },
    },
    {
      id: "[Ex: estX_teste_provadolaco]",
      tipo: "RESULTADO DE TESTE ESPECÍFICO",
      nomeTeste: "[Nome do Teste]",
      conteudo: {
        laudoResultado: "[Ex: Prova do Laço: Negativa (X petéquias no quadrado de 2,5 cm). OU Positiva (X petéquias).]",
        imagemRepresentativa: "(Opcional) Imagem representativa do resultado.",
      },
    },
  ],
  padraoEsperadoProcedimento: "[Pontos críticos da avaliação]",
  itensAvaliacao: {
    anamnese: {
      totalPontos: "[Total: X.X pontos]",
      apresentacaoAcolhimento: {
        descricao: "(1) Identifica-se (nome e/ou função); E (2) Cumprimenta o paciente simulado e pergunta seu nome (ou confirma).",
        pontos: 0.5,
        adequadas: 2,
        parcialmenteAdequadas: 1,
      },
      investigacaoQueixaPrincipal: {
        descricao: "Investiga pelo menos 4 dos seguintes: início, localização, irradiação, qualidade, intensidade, duração, fatores de melhora/piora, evolução.",
        pontos: 1.0,
        adequadas: 4,
        parcialmenteAdequadas: 2,
      },
      investigacaoSintomasAssociados: {
        descricao: "Pergunta sobre [Sintoma A], [Sintoma B], [Sintoma C], [Sintoma D] (listar 3-5 sintomas cruciais para o DDx).",
        pontos: 0.75,
        adequadas: 3,
        parcialmenteAdequadas: 1,
      },
      investigacaoSinaisAlarme: {
        descricao: "Pergunta sobre [Alarme 1], [Alarme 2], [Alarme 3], [Alarme 4] (listar 3-5 sinais de alarme).",
        pontos: 1.0,
        adequadas: 3,
        parcialmenteAdequadas: 1,
      },
      investigacaoAntecedentesPessoais: {
        descricao: "(1) Comorbidades; E (2) Medicações em uso; E (3) Alergias.",
        pontos: 0.75,
        adequadas: 3,
        parcialmenteAdequadas: 1,
      },
      investigacaoHabitosEpidemiologia: {
        descricao: "Investiga [Hábito 1 relevante, ex: tabagismo para SCA] E/OU [Dado epidemiológico relevante, ex: exposição a mosquitos para Dengue].",
        pontos: 0.5,
        adequadas: 1,
        parcialmenteAdequadas: 0, // Pode ajustar se houver lógica para parcial
      },
    },
    exameFisico: {
      totalPontos: "[Total: X.X pontos]",
      solicitaPermissao: {
        descricao: "Solicita permissão para realizar o exame fisico e solicita a presença de uma enfermeira/auxiliar de enfermagem (se mulher):",
        pontos: 0.125,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      higienizacaoParamentacao: {
        descricao: "Lavar e secar as mãos e vestir as luvas(ou se paramenta completamente com mascara, luvas estereis, oculos, avental, garrote e toca se sala vermelha/uti)",
        pontos: 0.125,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      solicitaSinaisVitais: {
        descricao: "(Considerar se já são fornecidos de início ou se o candidato precisa solicitar/simular a aferição).",
        pontos: 0.25,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      realizaExameDirecionado: {
        descricao: "Verbaliza os passos da inspeção, palpação, percussão e ausculta do sistema principal afetado.",
        pontos: 1.0,
        adequadas: 1,
        parcialmenteAdequadas: 0.5,
      },
      realizaManobraEspecifica: {
        descricao: "Descreve corretamente as etapas: [Etapa 1], [Etapa 2], [Etapa 3], [Etapa 4].",
        pontos: 1.0,
        adequadas: 4,
        parcialmenteAdequadas: 2,
      },
    },
    diagnostico: {
      totalPontos: "[Total: X.X pontos]",
      solicitaExamesPertinentes: {
        descricao: "Solicita [Exame Chave 1, ex: Hemograma] E [Exame Chave 2, ex: Sorologia para Dengue / ECG].",
        pontos: 0.75,
        adequadas: 2,
        parcialmenteAdequadas: 1,
      },
      interpretaResultados: {
        descricao: "Identifica as alterações principais nos exames fornecidos (se houver).",
        pontos: 0.75,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      verbalizaDiagnosticoClassificacao: {
        descricao: "Verbaliza o diagnóstico de [Diagnóstico Esperado] E sua classificação [Classificação Esperada, ex: Grupo A].",
        pontos: 1.0,
        adequadas: 1,
        parcialmenteAdequadas: 0.5,
      },
    },
    condutaComunicacao: {
      totalPontos: "[Total: X.X pontos]",
      elaboraComunicaCondutaInicial: {
        descricao: "Orienta [Medida 1, ex: Repouso e hidratação oral] E [Medida 2, ex: Paracetamol para dor/febre].",
        pontos: 1.0,
        adequadas: 2,
        parcialmenteAdequadas: 1,
      },
      orientaMedicacoesEvitar: {
        descricao: "Orienta a NÃO utilizar [Medicação a evitar 1, ex: AINEs] E/OU [Medicação a evitar 2, ex: AAS].",
        pontos: 0.75,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      orientaSinaisAlarmeRetorno: {
        descricao: "Orienta sobre [Alarme 1 para retorno], [Alarme 2 para retorno], [Alarme 3 para retorno] (listar 2-4 sinais).",
        pontos: 1.0,
        adequadas: 2,
        parcialmenteAdequadas: 1,
      },
      verbalizaNotificacaoCompulsoria: {
        descricao: "Adequado (0.5 pts): Verbaliza a necessidade de notificação (Ex: SINAN para Dengue).",
        pontos: 0.5,
        adequadas: 1,
        parcialmenteAdequadas: 0,
      },
      comunicacaoPaciente: {
        descricao: "(Avaliação global da comunicação durante a estação)",
        pontos: 0.5,
        adequadas: 1,
        parcialmenteAdequadas: 0.5,
      },
    },
  },
  bibliografiaReferencia: [
    "[Ex: Protocolo XYZ do Ministério da Saúde, Ano]",
  ],
  pontuacaoTotalEstacao: 10.0,
};

export type Station = typeof stationTemplate; // Optional: Export a type for clarity